backend:
  name: git-gateway
  commit_messages:
    create: âœ¨ - Create {{collection}} â€œ{{slug}}â€
    update: ğŸ“ƒ - Update {{collection}} â€œ{{slug}}â€
    delete: ğŸ—‘ - Delete {{collection}} â€œ{{slug}}â€
    uploadMedia: â¬†ï¸ - Upload â€œ{{path}}â€
    deleteMedia: ğŸš® - Delete â€œ{{path}}â€
media_folder: "src/static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "writing"
    format: "json"
    label: "Writing"
    folder: "src/content/writing"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
